language: ruby
rvm:
  - 2.1.4

branches:
  only:
    - develop

install: true

before_script:
  - gem update bundler
  - cd $(dirname $BUNDLE_GEMFILE)

gemfile:
  - engines/account/Gemfile
  - engines/group/Gemfile
  - engines/shared/Gemfile
  - engines/producers/Gemfile

script:
  - ./script/test.sh
