language: ruby
rvm:
  - 2.1.4

branches:
  only:
    - develop

install: true

before_script:
  - gem update bundler
  - cd $(dirname $BUNDLE_GEMFILE)

gemfile:
  - engines/shared/Gemfile
  - engines/account/Gemfile
  - engines/basic_resources/Gemfile
  - engines/products/Gemfile
  - engines/suppliers/Gemfile

script:
  - ./script/test.sh
