language: ruby
rvm:
  - 2.1.4

branches:
  only:
    - develop

before_install:
  - gem update bundler
  - cd $(dirname $BUNDLE_GEMFILE)

gemfile:
  - Gemfile
  - engines/account/Gemfile
  - engines/group/Gemfile
  - engines/shared/Gemfile

script:
  - ./script/test.sh
